using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using NOTESPACK.Data;
using NOTESPACK.Models;

namespace NOTESPACK.Services
{
    // Flat shape of a campus event for the seed file.
    // Intentionally excludes Id and UserId: Id is generated by the DB,
    // and UserId is always null (a "campus" event, not tied to a user).
    public record CampusEventSeedDto(
        string Title,
        string Description,
        DateTime Date,
        DateTime EndDate,
        string Duration,
        string Location,
        string Organizer
    );

    public static class CampusEventSeeder
    {
        // Called once on app startup (after Database.Migrate()).
        // Reads the JSON file and adds only the events that don't already exist
        // (same Title+Date deduplication logic used by the original sync service).
        public static async Task SeedFromFileAsync(IDbContextFactory<EventContext> contextFactory, string filePath)
        {
            if (!File.Exists(filePath))
            {
                Console.WriteLine($"CampusEventSeeder: seed file not found at '{filePath}'. Skipping seeding.");
                return;
            }

            List<CampusEventSeedDto>? seedEvents;
            try
            {
                var json = await File.ReadAllTextAsync(filePath);
                seedEvents = JsonSerializer.Deserialize<List<CampusEventSeedDto>>(
                    json,
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
                );
            }
            catch (Exception ex)
            {
                Console.WriteLine($"CampusEventSeeder: error reading/parsing '{filePath}': {ex.Message}");
                return;
            }

            if (seedEvents == null || seedEvents.Count == 0)
            {
                Console.WriteLine("CampusEventSeeder: seed file is empty. Nothing to load.");
                return;
            }

            using var context = contextFactory.CreateDbContext();

            var existingLookup = new HashSet<(string Title, DateTime Date)>(
                (await context.Events
                    .Select(e => new { e.Title, Date = e.Date.Date })
                    .ToListAsync())
                    .Select(e => (e.Title, e.Date))
            );

            var newEvents = new List<Event>();

            foreach (var dto in seedEvents)
            {
                var key = (dto.Title, dto.Date.Date);
                if (!existingLookup.Contains(key))
                {
                    newEvents.Add(new Event
                    {
                        Title = dto.Title,
                        Description = dto.Description,
                        Date = dto.Date.Date,
                        EndDate = dto.EndDate.Date,
                        Duration = dto.Duration,
                        Location = dto.Location,
                        Organizer = dto.Organizer,
                        UserId = null
                    });
                    existingLookup.Add(key);
                }
            }

            if (newEvents.Count > 0)
            {
                await context.Events.AddRangeAsync(newEvents);
                await context.SaveChangesAsync();
                Console.WriteLine($"CampusEventSeeder: loaded {newEvents.Count} campus events from the seed file.");
            }
            else
            {
                Console.WriteLine("CampusEventSeeder: no new events to load (all already existed).");
            }
        }
    }
}